### ISSUE TITLE
Server Crashes on start up when attempting to use this mod on a dedicated server

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [someaddons/Shieldmechanics#1]
**Describe the bug**
Whenever I try to set up a modded dedicated server with this mod installed, the server just crashes on start up.

**To Reproduce**
1. Set up a forge dedicated server
2. Install shield mechanics on this server.
3. start the server and wait.
4. After a little bit the server crashes.

**Expected behavior**
The server launches correctly and allows this mod to be used with it.

** Mod version **
1.4-1.16.5

** Logs **
Latest log: https://gist.github.com/NJL5390/cf288feab48aca1dd62ed34a013e4fbe
Crash Report: https://gist.github.com/NJL5390/0fc1a4abe28a91753ddd0dad5c6e3f43

**Comment by someaddons** [comment]
fixed
