### ISSUE TITLE
[Enhancement]: Can you change tooltip color to the ones of vanilla tooltip color?

### ISSUE THREAD

**Issue by murao-kun** [someaddons/Shieldmechanics#12]
### Describe the bug you're experiencing

Armor in vanilla minecraft have blue tooltip (+{number} armor). Tools and weapons have green tooltip ({number} attack damage).
Can we have at least have one of this ones instead of light green? I tried to make resource pack, but numbers color are hardcoded, so this is my result.
![image](https://user-images.githubusercontent.com/110398598/183303514-7558e8e9-2064-4478-a028-8833b24b8ab8.png)

### Reproducability

-

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

-

**Comment by murao-kun** [comment]
Any updates on this one?

**Comment by someaddons** [comment]
its blue in 1.19 now

**Comment by murao-kun** [comment]
Thank you!
