### ISSUE TITLE
[Bug]: Shield Expansion Mod Incompatibility

### ISSUE THREAD

**Issue by CheezBallzFTW** [someaddons/Shieldmechanics#16]
### Describe the bug you're experiencing

Can you make it compatible with Shield Expansion on Forge 1.19.2? Right now the shields block all damage when used with that mod.

### Reproducability

Block with a shield with Shield Expansion loaded with Shield Mechanics.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/CheezBallzFTW/0d3089956381a2d8a71d3b732d46b660

**Comment by someaddons** [comment]
that is a change the shield expansion mod would need to do, as it actively negates all damage
