### ISSUE TITLE
"Damage on block" Feature doesn't work when shield is in the off-hand

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [someaddons/Shieldmechanics#2]
**Describe the bug**
I noticed when testing this mod and it's shield mechanics that the "Damage on block" feature doesn't appear to work and shields still block 100% of damage regardless of what the config files say. 

**To Reproduce**
1. Install Shield Mechanics and create a new world.
2. Give yourself a shield and some weapons
3. Fight some mobs.
4. After fighting mobs for a bit you will notice that every hit on the shield will still block 100% of damage that is thrown it's way, no matter how many times the shield is hit.

**Expected behavior**
The shield would only block a certain percentage of melee damage that is thrown it's way. i.e 65% and you would still take some melee damage despite having the shield up as per the description on the curseforge page.

** Mod version **
1.5-1.16.5

** Logs **
Latest log: https://gist.github.com/NJL5390/5a43862f31b5e4fb7aa1af0d315e9dca

To attempt to show what I mean I spawned in a husk and let it hit me three times with my shield raised and none of them did any damage to me:

Before fighting husk:
![2021-05-01_12 22 20](https://user-images.githubusercontent.com/64381954/116781114-bdad9800-aa78-11eb-804c-94a10f40f666.png)

Immediately after:
![2021-05-01_12 22 35](https://user-images.githubusercontent.com/64381954/116781151-07967e00-aa79-11eb-83a2-349bac53a867.png)

**Comment by someaddons** [comment]
It does work, you probably just regenerated the little dmg that came through/never saw the damage happen. after 65% damage reduction there is not much left, and minecraft visually only displays when the damage is bigger than 1. So likely the damage did indeed happen you just never saw it

**Comment by The-Bernician-Lamb** [comment]
Hm, I see. That does help clear some confusion up. I'll test with a mob that has a higher damage output and see what happens.

**Comment by The-Bernician-Lamb** [comment]
Ok, I've discovered why I wasn't noticing any damage and what the actual issue is by testing with creepers. 

I've found that the blocking mechanics work properly when the shield is in your main hand but not if the shield is in your off hand:

(I started this test on 9.5 hearts)

After creeper explosion when shield is in the off hand (100% damage blocked):
![2021-05-01_18 32 45](https://user-images.githubusercontent.com/64381954/116790416-f0bd4f00-aaab-11eb-8995-38773842fd2c.png)

After creeper explosion when shield is in the main hand (3.5 hearts of damage):
![2021-05-01_18 33 01](https://user-images.githubusercontent.com/64381954/116790470-367a1780-aaac-11eb-8c6c-1287140cfa50.png)

When I use the shield in my main hand the damage on block feature works normally and I take damage as I'm supposed to, even from something like a zombie or husk.

When the shield is in my off-hand 100% of damage is blocked regardless, just like vanilla.

**Comment by someaddons** [comment]
oh I see, ye it probably ignores the off hand shield :D

**Comment by someaddons** [comment]
Should be fixed in version 1.6 now^^ btw thanks for the detailed reports

**Comment by The-Bernician-Lamb** [comment]
I can confirm that this is now fixed in Version 1.6! Thanks for your help!





>  btw thanks for the detailed reports

No problem! I always try my best to be as helpful and thorough as possible when submitting these bug reports! After all it only helps the issue get fixed faster!
