### ISSUE TITLE
Compat with Atum and Artifacts

### ISSUE THREAD

**Issue by D-Bigboy-302** [someaddons/Shieldmechanics#3]
Forge: 36.1.0
Atum: 2.2.5
Artifacts: 2.9.3

The shields in these mods don't appear to work with shield mechanics, even when put manually in the config. For Artifacts the only shield is the umbrella. I do play with optifine as well. In case that has an effect.

**Comment by someaddons** [comment]
should be working now

**Comment by D-Bigboy-302** [comment]
I'm getting this crash with the new version

[crash-2021-06-20_21.49.07-fml.txt](https://github.com/someaddons/Shieldmechanics/files/6683573/crash-2021-06-20_21.49.07-fml.txt)

Here's the latest log as well

[latest.log](https://github.com/someaddons/Shieldmechanics/files/6683576/latest.log)

**Comment by D-Bigboy-302** [comment]
Turns out the crash is just with artifacts. 

[crash-2021-06-21_07.59.57-fml.txt](https://github.com/someaddons/Shieldmechanics/files/6686454/crash-2021-06-21_07.59.57-fml.txt)

[latest.log](https://github.com/someaddons/Shieldmechanics/files/6686459/latest.log)
