### ISSUE TITLE
Crash with artifacts

### ISSUE THREAD

**Issue by D-Bigboy-302** [someaddons/Shieldmechanics#4]
Forge: 36.1.0
Artifacts: 2.9.3
Shield mechanics: 1.8

[crash-2021-06-21_21.23.07-fml.txt](https://github.com/someaddons/Shieldmechanics/files/6690326/crash-2021-06-21_21.23.07-fml.txt)

[latest.log](https://github.com/someaddons/Shieldmechanics/files/6690332/latest.log)

**Comment by The-Bernician-Lamb** [comment]
I'm also getting this issue. Started happening when I updated to 1.8. If I go back to 1.7 then it's all fine. 

My Crash Report: https://gist.github.com/NJL5390/ca1ef68498836f2efb01e355f9566661

**Comment by someaddons** [comment]
should work with 1.9, its asking the umbrella item if its a shield before the artifacts mod has its config loaded and crashes

**Comment by The-Bernician-Lamb** [comment]
Can confirm it's working for me with 1.9! Thanks a lot!
