### ISSUE TITLE
[1.16] Doesn't work with Tetra shields

### ISSUE THREAD

**Issue by CactusDuud** [someaddons/Shieldmechanics#5]
**Describe the bug**
When crafting Tetra shields, the new shield mechanics no longer apply.

**To Reproduce**
1. Install Tetra
2. Install Shield Mechanics
3. Make a Tetra shield
4. No shield mechanics :(

**Expected behavior**
Would be nice for the shield mechanics to still apply to Tetra shields.

** Mod version **
Shield Mechanics v2.1
Tetra v3.14.1

**Comment by someaddons** [comment]
v2.3 added some compat with those dynamic shield items, however they won't be configurable, outside of maximum configs
