### ISSUE TITLE
Not Working on Server

### ISSUE THREAD

**Issue by Charlobo** [someaddons/Shieldmechanics#6]
**Percentage damage reduction does not work on the server**

Hi, I like your mod very much, but I found that it works fine on the client-side, but percentage reduction doesn't work on the server-side. I have no idea why this problem occurs. I hope you will notice it and fix it.

**Percentage damage reduction does not work on the server**
Shield bash works perfect, but shields' percentage damage reduction does not work on the server
.

**Expected behavior**
On the server, shield could reduces damage by a percentage

** Mod version **

shieldmechanics-2.1-1.16.5

Mods used:
locks-1.16.5-3.0.3.jar
Login_Shield-1.16.5-5-g909ffa8.jar
OffHandCombat-1.16.3-3.2.0.3.jar
OnlyLooking-1.16.5-1.0.0.jar
parrying-1.10.0.jar
Penguin-Lib-1.16.5-0.4.1.jar
personality-1.16.5-1.0.2.jar
Placebo-1.16.4-4.5.0.jar
ProgressiveBosses-3.1.4-mc1.16.5.jar
PuzzlesLib-v1.0.7-1.16.5.jar
Quark-r2.4-314.jar
RealisticExplosionPhysics-1.16.5-1.0.0.jar
Regrowth-1.16.4-1.16.5-1.35.0.19.jar
SBM-Punt-Animal-1.16.5-1.0.0.jar
SchoolsOfMagic1.16.5-2.0.05.jar
selene-1.16.5-1.4.jar
shieldmechanics-2.1-1.16.5.jar
smoothboot-forge-1.16.4-1.2.2.jar
SnowRealMagic-1.16.4-2.5.7.jar
SoundFilters-0.14_for_1.16.2.jar
SpartanShields-1.16.5-2.1.2.jar
SpartanWeaponry-1.16.4-2.1.0-beta-4.jar
Spheric+1.0.3+1.16.5.jar
spiders-2.0-1.16.4-1.0.4.jar
stoneholm-1.2.2.jar
subwild-1.2.1.jar
supplementaries-1.16.5-0.14.4f.jar
sworddisplay-1.16.5-1.2.0.jar
tree_felling-2.3.jar
twoplayersonehorse-1.16.4-2.0.2.jar
upstream-1.0.jar
veldmg-1.16.5-1.0.0.jar
WeaponThrow-1.16.4-4.2.jar
xercapaint-1.16.5-1.0.jar
YungsApi-1.16.4-Forge-6.jar
[BETA]dannys_expansion1.16.5-1.0.9.1.jar
[Forge]+Rotten+Flesh+to+Leather+Orange+1.6.5.jar

**Comment by someaddons** [comment]
works just fine for me on a server, probably a mod conflict then. Which part exactly does not work for you?
