### ISSUE TITLE
[Compability Issue] can't die with HardcoreRevival

### ISSUE THREAD

**Issue by Romulus96** [someaddons/Shieldmechanics#7]
This seems to be a compability issue with HardcoreRevival, that is already known to the author: blay09/HardcoreRevival#55

If you have a shield equipped in your offhand and die, you can't give up and enter an infinite loop of K.Os. I am not sure if this is something that can be fixed on your end, or if this has to be fixed in HardcoreRevival.

## Technical Details
Minecraft 1.16.5
Forge 36.2.2
shieldmechanics-2.3-1.16.5
HardcoreRevival_1.16.5-6.0.1

**Comment by someaddons** [comment]
ye thats probably sth the hardcore revival mod needs to fix, shield mechanics only uses the living damage events to alter the percentage of damage received
