### ISSUE TITLE
I don't know what mod causes the shield defense value to be inconsistent

### ISSUE THREAD

**Issue by nitbe** [someaddons/Shieldmechanics#9]
**Describe the bug**
mod causes the shield defense value to be inconsistent

**To Reproduce**
When I set the shield defense to 65, it becomes 71 when I enter the game, and the value is different every time I enter the game，sometime 71，68

** Mod version **
shieldmechanics-2.4-1.16.5.jar

**Comment by someaddons** [comment]
can't reproduce, probably your config doesnt save properly/gets corrupted
